inherit_from: ../.rubocop_todo.yml
AllCops:
  Exclude:
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb
    - config/**/*

# Customize rules
Metrics/LineLength:
  Max: 250

MethodLength:
  Enabled: false

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LineLength:
  Enabled: false

Lint/Eval:
  Exclude:
    - 'app/helpers/calculations_helper.rb'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/views/home/index.html.erb_spec.rb'
