AllCops:
  Excludes:
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb

# Customize rules
Metrics/LineLength:
  Enabled: false

MethodLength:
  Max: 250

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Max: 250
