AllCops:
  Exclude:
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb

# Customize rules
Metrics/LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
