AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

# Customize rules
Metrics/LineLength:
  Max: 250

MethodLength:
  Enabled: false

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false
